[files]
extend-exclude = [
  "docs/jenkins/config/*.yaml",
  "docs/devops/klocwork/klocwork_web_api.html",
  "docs/linux/ubuntu/shadowsocks-all.sh"
]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode=true
locale = "en"
extend-ignore-re = [
  '(sed|awk|grep|tar|bash|set)\s+-[a-zA-Z]+',
  '\s-[a-zA-Z]+',
  # [c]ommit, d[i]ff, ...
  "\\w*\\[\\w\\]\\w*",
  '\w*\[\w+\]\w*',
  '\w*\(\w\)\w+',
  # ansicolor
  "\\w+=.*\\\\033.*",
  "\\w*\\\\033\\S+",
  # vim modeline
  "(?m)^.*\\bvim:.*$",
  "PS1=.*",
  # regex: (?:xxx)
  '\(\?:.*?\)',
  # regex: ^\s*(...)
  '\^\\s\*\(.*?\)',
  # regex: \b(...)
  '\\b\(.*?\)',
  # regex: (?=\s*
  '\(\?=\\s\*',
  # regex: '...'.split("(?=...)
  '.*split\("\(\?=.*',
  # token
  '[A-Za-z0-9+/]{40,}={0,2}',
  '// result:.*'
]

[default.extend-words]
# <typo> = "<correction>"
ba = 'ba'
certifi = 'certifi'
fpr = 'fpr'
fo = 'fo'
enhancd = 'enhancd'
HPE = 'HPE'
storaged = 'storaged'
STRIN = 'STRIN'
chage = 'chage'
Froms = 'Froms'
UDID = 'UDID'
captin = 'captin'
dbe = 'dbe'
Dbe = 'Dbe'
ue = 'ue'
nd = 'nd'
comman = 'comman'
IST = 'IST'
Cpy = 'Cpy'
stap = 'stap'
alis = 'alis'
issu = 'issu'
mak = 'mak'
nin = 'nin'
Pn = 'Pn'
Activ = 'Activ'
juli = 'juli'
flate = 'flate'
Divy = 'Divy'
ALS = 'ALS'
enew = 'enew'
nd6 = 'nd6'
Informations = 'Informations'
cicle = 'cicle'
Infared = 'Infared'
Compatability = 'Compatability'
Seperator = 'Seperator'
# HashiCorp
Hashi= 'Hashi'
synopsys = 'synopsys'
MICROSFT = 'MICROSFT'
